#!/usr/bin/env bash
set -e # exit when error

# Use this with `npm run build` so that `./node_modules/.bin` are injected into
# the PATH

license="/*! cliniasearch ${VERSION:-UNRELEASED} | © 2019 Clinia | github.com/clinia/cliniasearch-client-javascript */"

echo 'Building cliniasearch-client-js'

bundles=( 'cliniasearch' 'cliniasearch.angular' 'cliniasearch.jquery' )

echo '..Add browserify bundles'
# cannot use a loop, bundles are different (--standalone)
browserify -p bundle-collapser/plugin src/browser/builds/cliniasearch.js --standalone cliniasearch >> dist/cliniasearch.js
browserify -p bundle-collapser/plugin src/browser/builds/cliniasearch.angular.js >> dist/cliniasearch.angular.js
browserify -p bundle-collapser/plugin src/browser/builds/cliniasearch.jquery.js >> dist/cliniasearch.jquery.js

echo '..Minify'
for bundle in "${bundles[@]}"
do
  uglifyjs dist/"$bundle".js -mc 'warnings=false' > dist/"$bundle".min.js
done

echo '..Prepend license'
# We prepend the license to be sure it's always present, no matter the used minifier
# http://www.cyberciti.biz/faq/bash-prepend-text-lines-to-file/
for bundle in "${bundles[@]}"
do
  echo "$license" | cat - dist/"$bundle".js > /tmp/out && mv /tmp/out dist/"$bundle".js
  echo "$license" | cat - dist/"$bundle".min.js > /tmp/out && mv /tmp/out dist/"$bundle".min.js
done

echo '..Gzipped file size'
for bundle in "${bundles[@]}"
do
  echo "${bundle}.min.js gzipped will weigh" $(cat dist/"${bundle}".min.js | gzip -9 | wc -c | pretty-bytes)
done

# not in the same loop as previous builds: no compatibility layer
echo '..Lite build'
browserify -p bundle-collapser/plugin src/browser/builds/cliniasearchLite.js --standalone cliniasearch > dist/cliniasearchLite.js
uglifyjs dist/cliniasearchLite.js -mc 'warnings=false' > dist/cliniasearchLite.min.js
echo "$license" | cat - dist/cliniasearchLite.js > /tmp/out && mv /tmp/out dist/cliniasearchLite.js
echo "$license" | cat - dist/cliniasearchLite.min.js > /tmp/out && mv /tmp/out dist/cliniasearchLite.min.js
echo "cliniasearchLite.min.js gzipped will weigh" $(cat dist/cliniasearchLite.min.js | gzip -9 | wc -c | pretty-bytes)

echo 'Done'